[tool]
id = "com.thelightphone.tracker"
label = "Tracker"
versionCode = 39
versionName = "2.5.0"
permissions = []
# change if you run this on an LP3!
# serverPackage = "com.lightos"
serverPackage = "com.thelightphone.sdk.emulator"
