[tool]
id = "com.thelightphone.tracker"
label = "Tracker"
versionCode = 20
versionName = "1.6.2"
permissions = []
# change if you run this on an LP3!
# serverPackage = "com.lightos"
serverPackage = "com.thelightphone.sdk.emulator"
